targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake_case
          include_if_null: false
          explicit_to_json: true
      freezed:
        options:
          map: true
          make_constructor_generic: true